## Hi there 👋

<!--
**Sajid-Kabir/Sajid-Kabir** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-  Build Apps For You 
-  About Us;
Sk Sajid...

Mail:sksajid201805079@gmail.com 

Facebook Page :
https://www.facebook.com/Sk-Sajid-102738785136869/

Youtube link: link:https://youtube.com/channel/UC7YOfPVJnj8fzQBvHceTKvw

Our website :
kabirmd.blogspot.com
&
parsonalblog.blogspot.com

Telegram Link:
Sk Sajid
https://t.me/sksajidraj
